apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  name: ci-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: perf.ci.openmina.com
    http:
      paths:
      - backend:
          service:
            name: ci-frontend-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - perf.ci.openmina.com
    secretName: ingress-tls
