---
apiVersion: v1
kind: Service
metadata:
  name: {{$.Values.coordinatorName }}-graphql
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  selector:
    app: {{$.Values.coordinatorName }}
  ports:
  - name: http-graphql
    protocol: TCP
    port: 80
    targetPort: {{ $.Values.mina.ports.graphql }}
